from database.table.author_table import AuthorTable
from database.table.translator_table import TranslatorTable
from database.table.genre_table import GenreTable
from database.table.finish_status_table import FinishStatusTable
from database.table.comic_translator_table import ComicTranslatorTable
from database.table.comic_table import ComicTable
from database.table.comic_genre_table import ComicGenreTable
from database.table.comic_author_table import ComicAuthorTable
from database.table.chapter_table import ChapterTable
from database.table.page_table import PageTable
